version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rococo
      - MYSQL_DATABASE=task
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=chocorrococo123
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: